// The generated file may or may not exist when typechecking, so ts-expect-error won't fit.
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore `.open-next/worker.js` is generated by `opennextjs-cloudflare build`
import { default as handler } from "./.open-next/worker.js";

type RateLimitBinding = {
  limit(options: { key: string }): Promise<{ success: boolean }>;
};

type WorkerEnv = Record<string, unknown> & { API_RATE_LIMITER?: RateLimitBinding };

type OpenNextHandler = {
  fetch(request: Request, env: WorkerEnv, ctx: unknown): Promise<Response>;
};

const RETRY_AFTER_SECONDS = 60;

function tooManyRequests(): Response {
  return new Response(JSON.stringify({ error: "Too many requests. Try again in a minute." }), {
    status: 429,
    headers: {
      "content-type": "application/json; charset=utf-8",
      "retry-after": String(RETRY_AFTER_SECONDS),
      "cache-control": "no-store",
    },
  });
}

const worker = {
  async fetch(request: Request, env: WorkerEnv, ctx: unknown): Promise<Response> {
    const { pathname } = new URL(request.url);
    // Internal subrequests (service binding, cache revalidation) carry no client IP.
    const ip = request.headers.get("cf-connecting-ip");
    if (pathname.startsWith("/api/") && ip && env.API_RATE_LIMITER) {
      const { success } = await env.API_RATE_LIMITER.limit({ key: `api:${ip}` });
      if (!success) return tooManyRequests();
    }
    return (handler as OpenNextHandler).fetch(request, env, ctx);
  },
};

export default worker;

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore `.open-next/worker.js` is generated by `opennextjs-cloudflare build`
export { DOQueueHandler, DOShardedTagCache, BucketCachePurge } from "./.open-next/worker.js";
