/**
 * Sync approved portrait URL map (generated by P18B.5.1).
 * Keys: NBA PERSON_ID and ESPN athlete id → verified asset URL.
 *
 * IMPORTANT (Cloudflare Workers): keep this JSON on the module graph. Workers'
 * virtual `node:fs` does not mount OpenNext traced files, so disk reads return
 * empty and every headshot falls through to initials.
 */
import portraitLookupJson from "@/data/media/portrait-lookup.json";

export type PortraitLookupFile = {
  version: string;
  portraits: Record<string, string>;
  count: number;
};

const file = portraitLookupJson as PortraitLookupFile;
const portraits: Record<string, string> =
  file?.portraits && typeof file.portraits === "object" ? file.portraits : {};

export function loadPortraitLookup(): PortraitLookupFile | null {
  if (!Object.keys(portraits).length) return null;
  return {
    version: file.version ?? "bundled",
    portraits,
    count: file.count ?? Object.keys(portraits).length,
  };
}

/** Clear memo (tests / rebuild) — no-op for the bundled map. */
export function clearPortraitLookupCache() {
  // Bundled map is immutable for the Worker lifetime.
}

export function lookupApprovedPortraitUrl(
  ...ids: Array<string | null | undefined>
): string | null {
  for (const id of ids) {
    if (!id) continue;
    const key = String(id);
    const url =
      portraits[key] ??
      portraits[`espn:${key}`] ??
      null;
    if (url) return url;
  }
  return null;
}
