/**
 * Sync approved portrait URL map (generated by P18B.5.1).
 * Keys: NBA PERSON_ID and ESPN athlete id → verified asset URL.
 */
import { existsSync, readFileSync } from "node:fs";
import path from "node:path";

export type PortraitLookupFile = {
  version: string;
  portraits: Record<string, string>;
  count: number;
};

let cache: PortraitLookupFile | null | undefined;

function tryParse(p: string): PortraitLookupFile | null {
  if (!existsSync(p)) return null;
  try {
    return JSON.parse(readFileSync(p, "utf8")) as PortraitLookupFile;
  } catch {
    return null;
  }
}

export function loadPortraitLookup(): PortraitLookupFile | null {
  if (cache !== undefined) return cache;
  const root = process.cwd();
  const candidates = [
    path.join(root, "src", "data", "media", "portrait-lookup.json"),
    path.join(
      root,
      "data",
      "drbl",
      "player-media",
      "drbl-player-media-v2",
      "portrait-lookup.json"
    ),
    path.join(
      root,
      "data",
      "drbl",
      "player-media",
      "drbl-player-media-v1",
      "portrait-lookup.json"
    ),
  ];
  for (const p of candidates) {
    const parsed = tryParse(p);
    if (parsed?.portraits) {
      cache = parsed;
      return cache;
    }
  }
  cache = null;
  return null;
}

/** Clear memo (tests / rebuild). */
export function clearPortraitLookupCache() {
  cache = undefined;
}

export function lookupApprovedPortraitUrl(
  ...ids: Array<string | null | undefined>
): string | null {
  const lookup = loadPortraitLookup();
  if (!lookup) return null;
  for (const id of ids) {
    if (!id) continue;
    const key = String(id);
    const url =
      lookup.portraits[key] ??
      lookup.portraits[`espn:${key}`] ??
      null;
    if (url) return url;
  }
  return null;
}
