/**
 * Sync approved portrait URL map (generated by P18B.5.1).
 * Keys: NBA PERSON_ID and ESPN athlete id → verified asset URL.
 *
 * IMPORTANT (Cloudflare Workers): keep this JSON on the module graph. Workers'
 * virtual `node:fs` does not mount OpenNext traced files, so disk reads return
 * empty and every headshot falls through to initials.
 */
import legendPortraitsJson from "@/data/media/legend-portraits.json";
import portraitFallbacksJson from "@/data/media/portrait-fallbacks.json";
import portraitLookupJson from "@/data/media/portrait-lookup.json";

export type PortraitLookupFile = {
  version: string;
  portraits: Record<string, string>;
  count: number;
};

/** Basketball-Reference's headshots aren't ours to hotlink; those players show initials instead. */
const BLOCKED_PORTRAIT_HOST = /^https?:\/\/(?:www\.)?basketball-reference\.com\//;

function allowedPortraits(map: Record<string, string> | undefined): Record<string, string> {
  if (!map || typeof map !== "object") return {};
  return Object.fromEntries(
    Object.entries(map).filter(([, url]) => typeof url === "string" && !BLOCKED_PORTRAIT_HOST.test(url))
  );
}

const file = portraitLookupJson as PortraitLookupFile;
const portraits = allowedPortraits(file?.portraits);
/** Routes the registry misses (scripts/build-player-photo-fallbacks.ts). */
const fallbacks = allowedPortraits(
  (portraitFallbacksJson as { portraits?: Record<string, string> }).portraits
);
/**
 * Playing-days photos for pre-1996-97 players (scripts/build-legend-portraits.ts).
 * Wins over the registry, whose legend entries are often post-career shots.
 */
const legends = allowedPortraits(
  (legendPortraitsJson as { portraits?: Record<string, string> }).portraits
);

export function loadPortraitLookup(): PortraitLookupFile | null {
  if (!Object.keys(portraits).length) return null;
  return {
    version: file.version ?? "bundled",
    portraits,
    count: Object.keys(portraits).length,
  };
}

/** Clear memo (tests / rebuild) — no-op for the bundled map. */
export function clearPortraitLookupCache() {
  // Bundled map is immutable for the Worker lifetime.
}

function lookupIn(
  map: Record<string, string>,
  ids: Array<string | null | undefined>
): string | null {
  for (const id of ids) {
    if (!id) continue;
    const key = String(id);
    const url = map[key] ?? map[`espn:${key}`] ?? null;
    if (url) return url;
  }
  return null;
}

/** Main registry only (what scripts/build-player-photo-fallbacks.ts fills around). */
export function lookupRegistryPortraitUrl(
  ...ids: Array<string | null | undefined>
): string | null {
  return lookupIn(portraits, ids);
}

export function lookupApprovedPortraitUrl(
  ...ids: Array<string | null | undefined>
): string | null {
  return lookupIn(legends, ids) ?? lookupIn(portraits, ids) ?? lookupIn(fallbacks, ids);
}
